### ISSUE TITLE
No hacer migraciones automáticamente al arrancar

### ISSUE THREAD

**Issue by astrojuanlu** [Mercado-Social-de-Madrid/ansible-takahe#6]
Observamos que, cuando se quiere restaurar una copia de la base de datos, es mejor no hacer las migraciones automáticamente tras el despliegue.

**Comment by astrojuanlu** [comment]
Lo suyo parece ser definir un servicio tipo:

```yaml

  migration:
    container_name: migration
    image: jointakahe/takahe:0.10
    command: python3 manage.py migrate
    env_file: .env
    depends_on:
      - db
```

con el que poder hacer las migraciones. Investigar un poco más.
